---
- name: Copy motd on newer Debian systems
  block:
    - name: cp motd-sh /etc/update-motd.d/
      copy:
        src: motd-sh
        dest: /etc/update-motd.d/99-homeco
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: remove noisy MOTD files
      file:
        path: /etc/update-motd.d/{{ item }}
        state: absent
        modification_time: preserve
        access_time: preserve
      with_items:
        - 00-header
        - 10-help-text
        - 10-uname
        - 50-motd-news
        - 50-landscape-sysinfo
        - 80-esm
        - 90-updates-available
        - 91-release-upgrade
        - 92-unattended-upgrades
        - 98-fsck-at-reboot
        - 95-hwe-eol
        - 97-overlayroot
  when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int >= 9

# On old Debian systems the Banner is enabled in sshd and we are able to use issue.net
# These old systems don't have the dynamic motd feature
- name: cp motd /etc/issue.net
  copy:
    src: motd-static
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 644
  when: ansible_os_family == 'Debian' and ansible_distribution_major_version|int < 9

- name: cp motd /etc/motd
  copy:
    src: motd-static
    dest: /etc/motd
    owner: root
    group: root
    mode: 644
  when: ansible_os_family == 'RedHat'
